spring:
  data:
   mongodb:
     uri: mongodb+srv://${USER_DB:admin}:${PASSWORD_DB}@webfluxcoursecluster.lfmssz0.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority
     auto-index-creation: true
  application:
    name: webflux-course

springdoc:
  api-docs:
    enabled: true